name: Rust Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        toolchain: [stable]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.toolchain }}
        override: true

    - name: Build
      run: cargo build

    - name: Run tests
      run: cargo test

    - name: Run tests (no default features)
      run: cargo test --no-default-features

    - name: Rustfmt
      run: cargo fmt --check
